"""Helpers for SageMaker pipeline naming and scaffolding.

This module contains small utility functions that keep ML naming conventions
consistent while the wider training and promotion workflow is being built.

Examples
--------
>>> build_training_job_name("energyops-dev-creative-antelope", "forecast-xgb")
'energyops-dev-creative-antelope-forecast-xgb-train'
>>> build_model_package_group_name("energyops-dev-creative-antelope", "forecast")
'energyops-dev-creative-antelope-forecast-registry'
"""


def build_training_job_name(deployment_name: str, model_family: str) -> str:
    """
    Create a readable training job name from the deployment and model family.

    Parameters
    ----------
    deployment_name : str
        Shared deployment name generated by infrastructure setup.
    model_family : str
        Short model-family identifier, for example `forecast-xgb`.

    Returns
    -------
    str
        Training job name in the form `<deployment>-<model-family>-train`.

    Notes
    -----
    Keeping training job names deterministic makes CloudWatch logs,
    SageMaker jobs, and deployment diagnostics easier to correlate.

    Examples
    --------
    >>> build_training_job_name("energyops-dev-creative-antelope", "forecast-xgb")
    'energyops-dev-creative-antelope-forecast-xgb-train'
    """

    return f"{deployment_name}-{model_family}-train"


def build_model_package_group_name(deployment_name: str, model_family: str) -> str:
    """
    Create a readable SageMaker model package group name.

    Parameters
    ----------
    deployment_name : str
        Shared deployment name generated by infrastructure setup.
    model_family : str
        Short model-family identifier, for example `forecast` or `anomaly`.

    Returns
    -------
    str
        Model package group name in the form
        `<deployment>-<model-family>-registry`.

    Notes
    -----
    Model package groups form the backbone of SageMaker Model Registry. Using
    deterministic names keeps registration, approval, and deployment workflows
    easier to trace through the AWS console and API responses.

    Examples
    --------
    >>> build_model_package_group_name("energyops-dev-creative-antelope", "forecast")
    'energyops-dev-creative-antelope-forecast-registry'
    """

    return f"{deployment_name}-{model_family}-registry"
