"""Helpers for SageMaker pipeline naming and scaffolding.

This module contains small utility functions that keep ML naming conventions
consistent while the wider training and promotion workflow is being built.

Examples
--------
>>> build_training_job_name("energyops-dev-creative-antelope", "forecast-xgb")
'energyops-dev-creative-antelope-forecast-xgb-train'
"""


def build_training_job_name(deployment_name: str, model_family: str) -> str:
    """
    Create a readable training job name from the deployment and model family.

    Parameters
    ----------
    deployment_name : str
        Shared deployment name generated by infrastructure setup.
    model_family : str
        Short model-family identifier, for example `forecast-xgb`.

    Returns
    -------
    str
        Training job name in the form `<deployment>-<model-family>-train`.

    Notes
    -----
    Keeping training job names deterministic makes CloudWatch logs,
    SageMaker jobs, and deployment diagnostics easier to correlate.

    Examples
    --------
    >>> build_training_job_name("energyops-dev-creative-antelope", "forecast-xgb")
    'energyops-dev-creative-antelope-forecast-xgb-train'
    """

    return f"{deployment_name}-{model_family}-train"
