# Region is passed explicitly so the module follows the shared project
# context rather than whichever AWS CLI region happens to be active.
variable "aws_region" {
  type        = string
  description = "AWS region for IAM-related deployment context"
}

# The deployment name keeps IAM resources aligned with the rest of the stack.
variable "deployment_name" {
  type        = string
  description = "Shared deployment name generated by the project context module"
}

# These ARNs are passed in from earlier modules so IAM permissions can stay
# scoped to this project's actual buckets and KMS key.
variable "kms_key_arn" {
  type        = string
  description = "KMS key ARN used by the execution roles"
}

variable "lakehouse_bucket_arn" {
  type        = string
  description = "ARN of the main S3 lakehouse bucket"
}

variable "artefact_bucket_arn" {
  type        = string
  description = "ARN of the model artefact bucket"
}

variable "monitoring_bucket_arn" {
  type        = string
  description = "ARN of the monitoring bucket"
}

variable "lambda_role_name" {
  type        = string
  description = "Explicit Lambda role name"
  default     = null
}

variable "glue_role_name" {
  type        = string
  description = "Explicit Glue role name"
  default     = null
}

variable "sagemaker_role_name" {
  type        = string
  description = "Explicit SageMaker execution role name"
  default     = null
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to IAM resources"
  default     = {}
}
