# Region is passed explicitly so the schedule is created in the same region as
# the rest of the platform regardless of local CLI defaults.
variable "aws_region" {
  type        = string
  description = "AWS region for the Silver-to-Gold scheduler resources."
}

# The deployment name comes from the shared project-context module so naming
# remains stable and recognisable across all downstream resources.
variable "deployment_name" {
  type        = string
  description = "Shared deployment name generated by the project context module."
}

# The scheduler needs both the Glue job name and ARN:
# - the name is sent to the StartJobRun API payload
# - the ARN is used to scope the IAM permission narrowly
variable "glue_job_name" {
  type        = string
  description = "Name of the Silver-to-Gold Glue job started by the scheduler."
}

variable "glue_job_arn" {
  type        = string
  description = "ARN of the Silver-to-Gold Glue job started by the scheduler."
}

variable "schedule_name" {
  type        = string
  description = "Explicit EventBridge Scheduler schedule name."
  default     = null
}

variable "scheduler_role_name" {
  type        = string
  description = "Explicit IAM role name used by the scheduler target."
  default     = null
}

variable "group_name" {
  type        = string
  description = "Scheduler group name."
  default     = "default"
}

variable "description" {
  type        = string
  description = "Description of the Silver-to-Gold scheduler."
  default     = "Recurring EventBridge Scheduler trigger for the Silver-to-Gold Glue job."
}

# A cadence-based schedule keeps orchestration lightweight. If stricter
# sequencing is needed later, this can be replaced with event-driven workflow
# orchestration without changing the Glue job module itself.
variable "schedule_expression" {
  type        = string
  description = "Scheduler rate or cron expression."
  default     = "rate(30 minutes)"
}

variable "schedule_expression_timezone" {
  type        = string
  description = "Timezone used when evaluating the schedule expression."
  default     = "UTC"
}

variable "schedule_state" {
  type        = string
  description = "State of the schedule."
  default     = "ENABLED"
}

# Optional job arguments allow later runs to override or enrich the Glue job
# invocation without changing the Terraform module shape.
variable "job_run_arguments" {
  type        = map(string)
  description = "Optional per-run arguments passed to Glue StartJobRun."
  default     = {}
}

variable "job_run_queuing_enabled" {
  type        = bool
  description = "Whether Glue job run queuing should be enabled for scheduled runs."
  default     = false
}

variable "maximum_event_age_in_seconds" {
  type        = number
  description = "Maximum age of the schedule event before it is discarded."
  default     = 3600
}

variable "maximum_retry_attempts" {
  type        = number
  description = "Maximum number of retry attempts for failed schedule invocations."
  default     = 1
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to scheduler resources."
  default     = {}
}
