variable "aws_region" {
  type        = string
  description = "AWS region for the KMS key"
}

variable "deployment_name" {
  type        = string
  description = "Shared deployment name generated by the project context module"
}

variable "kms_key_alias_name" {
  type        = string
  description = "Explicit KMS alias name. If null, uses kms_key_alias_prefix plus deployment_name"
  default     = null
}

variable "kms_key_alias_prefix" {
  type        = string
  description = "Prefix used to build the KMS alias"
  default     = "alias/kms"
}

variable "description" {
  type        = string
  description = "Description for the KMS key"
  default     = "KMS key for the AWS energy forecasting platform"
}

variable "enable_key_rotation" {
  type        = bool
  description = "Enable automatic yearly key rotation"
  default     = true
}

variable "deletion_window_in_days" {
  type        = number
  description = "Deletion window for the KMS key"
  default     = 7
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to the KMS resources"
  default     = {}
}

