# Region is passed explicitly so the schedule is created in the same region
# as the rest of the platform regardless of local CLI defaults.
variable "aws_region" {
  type        = string
  description = "AWS region for the EventBridge Scheduler resources"
}

# The environment and deployment name are passed from the shared project
# context so naming and tagging remain consistent across modules.
variable "environment" {
  type        = string
  description = "Deployment environment"
}

variable "deployment_name" {
  type        = string
  description = "Shared deployment name generated by the project context module"
}

# The scheduler needs both the function name and ARN:
# - ARN for the schedule target
# - name for the Lambda permission resource
variable "lambda_function_name" {
  type        = string
  description = "Name of the Lambda function invoked by the scheduler"
}

variable "lambda_function_arn" {
  type        = string
  description = "ARN of the Lambda function invoked by the scheduler"
}

variable "schedule_name" {
  type        = string
  description = "Explicit EventBridge Scheduler schedule name"
  default     = null
}

variable "scheduler_role_name" {
  type        = string
  description = "Explicit IAM role name for the scheduler target role"
  default     = null
}

variable "group_name" {
  type        = string
  description = "Scheduler group name"
  default     = "default"
}

variable "description" {
  type        = string
  description = "Description of the schedule"
  default     = "Near-real-time ingestion schedule for the energy forecasting Lambda"
}

# Use a rate expression by default to keep the first ingestion flow easy to
# understand and adjust. Cron expressions can be supplied later if needed.
variable "schedule_expression" {
  type        = string
  description = "Scheduler rate or cron expression"
  default     = "rate(30 minutes)"
}

variable "schedule_expression_timezone" {
  type        = string
  description = "Timezone used when evaluating the schedule expression"
  default     = "UTC"
}

variable "schedule_state" {
  type        = string
  description = "State of the schedule"
  default     = "ENABLED"
}

# The payload is passed straight through to the Lambda on each scheduled
# invocation so the schedule can carry lightweight runtime context.
variable "scheduler_payload" {
  type        = map(string)
  description = "JSON payload delivered to the Lambda target on each invocation"
  default = {
    trigger = "eventbridge-scheduler"
    source  = "ingestion"
  }
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to scheduler resources"
  default     = {}
}

