variable "aws_region" {
  type        = string
  description = "AWS region for the Lambda function"
}

variable "environment" {
  type        = string
  description = "Deployment environment"
}

variable "deployment_name" {
  type        = string
  description = "Shared deployment name generated by the project context module"
}

variable "kms_key_arn" {
  type        = string
  description = "KMS key ARN used to encrypt Lambda environment variables and logs"
}

variable "lambda_role_arn" {
  type        = string
  description = "IAM role ARN assumed by the ingestion Lambda"
}

variable "lakehouse_bucket_name" {
  type        = string
  description = "S3 lakehouse bucket used to store Bronze ingestion outputs"
}

variable "lambda_function_name" {
  type        = string
  description = "Explicit Lambda function name"
  default     = null
}

variable "runtime" {
  type        = string
  description = "Lambda runtime"
  default     = "python3.12"
}

variable "handler" {
  type        = string
  description = "Lambda handler entry point"
  default     = "app.handler"
}

variable "architecture" {
  type        = string
  description = "Lambda architecture"
  default     = "x86_64"
}

variable "memory_size" {
  type        = number
  description = "Lambda memory size in MB"
  default     = 256
}

variable "timeout_seconds" {
  type        = number
  description = "Lambda timeout in seconds"
  default     = 60
}

variable "log_retention_in_days" {
  type        = number
  description = "CloudWatch log retention period"
  default     = 14
}

variable "bronze_ingestion_prefix" {
  type        = string
  description = "S3 prefix used by the ingestion Lambda"
  default     = "bronze/ingestion-manifests"
}

variable "energy_api_base_url" {
  type        = string
  description = "Base URL for the public electricity data source"
  default     = "https://data.elexon.co.uk"
}

variable "weather_api_base_url" {
  type        = string
  description = "Base URL for the public weather data source"
  default     = "https://api.open-meteo.com"
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to the Lambda resources"
  default     = {}
}

