variable "aws_region" {
  type        = string
  description = "AWS region for the S3 buckets"
}

variable "deployment_name" {
  type        = string
  description = "Shared deployment name generated by the project context module"
}

variable "kms_key_arn" {
  type        = string
  description = "KMS key ARN used for bucket encryption"
}

variable "lakehouse_bucket_name" {
  type        = string
  description = "Explicit S3 bucket name for the lakehouse bucket"
  default     = null
}

variable "artefact_bucket_name" {
  type        = string
  description = "Explicit S3 bucket name for the model artefact bucket"
  default     = null
}

variable "monitoring_bucket_name" {
  type        = string
  description = "Explicit S3 bucket name for the monitoring bucket"
  default     = null
}

variable "force_destroy" {
  type        = bool
  description = "Allow Terraform to delete non-empty buckets"
  default     = false
}

variable "create_lakehouse_prefixes" {
  type        = bool
  description = "Create starter prefixes in the lakehouse bucket"
  default     = true
}

variable "lakehouse_prefixes" {
  type        = list(string)
  description = "Starter prefixes created inside the lakehouse bucket"
  default     = ["bronze", "silver", "gold", "feature_store", "training", "inference", "monitoring"]
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to the buckets"
  default     = {}
}

